execute_process(
	COMMAND ${GIT_EXECUTABLE} describe --tags --dirty=M
	OUTPUT_VARIABLE GIT_VERSION
	RESULT_VARIABLE GIT_DESCRIBE_RESULT
	ERROR_VARIABLE GIT_DESCRIBE_ERROR
	OUTPUT_STRIP_TRAILING_WHITESPACE
)

execute_process(
	COMMAND ${GIT_EXECUTABLE} show -s --pretty=%cd --date=short HEAD
	OUTPUT_VARIABLE GIT_DATE
	RESULT_VARIABLE GIT_SHOW_RESULT
	ERROR_VARIABLE GIT_SHOW_ERROR
	OUTPUT_STRIP_TRAILING_WHITESPACE
)

configure_file(${INPUT_FILE} ${OUTPUT_FILE})

