# Makefile for building extra dependencies from Visual Studio.

# The grfcodec source directory, in Cygwin
SOURCE_DIR = ~/grfcodec

all:
	/bin/sh -c "export PATH=\"/bin\" && make -C $(SOURCE_DIR) ttdpal.h version.h NO_MAKEFILE_DEP=1"
