# Makefile for building extra dependencies from Visual Studio.

# The grfcodec source directory, in Cygwin
SOURCE_DIR = ~/grfcodec

all:
ifneq ($(NOREV),0)
	/bin/sh -c "export PATH=\"/bin\" && rm -f version.h && make -C $(SOURCE_DIR) ttdpal.h version.h && touch .rev"
else
	/bin/sh -c "export PATH=\"/bin\" && make -C $(SOURCE_DIR)  ttdpal.h version.h"
endif
