error.o: error.c error.h typesize.h
getopt.o: getopt.c ./getopt.h
grfcomm.o: grfcomm.c error.h typesize.h path.h grfcomm.h
grfmerge.o: grfmerge.c ./getopt.h typesize.h version.h
path.o: path.c path.h typesize.h
grfcodec.o: grfcodec.cc ./getopt.h pcx.h typesize.h sprites.h pcxsprit.h \
  ttdpal.h grfcomm.h info.h nfosprite.h AllocArray.h error.h version.h \
  conv.h path.h
grfdiff.o: grfdiff.cc ./getopt.h error.h typesize.h sprites.h pcx.h \
  grfcomm.h grfmrg.h path.h version.h
info.o: info.cc info.h pcxsprit.h pcx.h typesize.h sprites.h nfosprite.h \
  AllocArray.h error.h
pcx.o: pcx.cc pcx.h typesize.h error.h
pcxsprit.o: pcxsprit.cc pcxsprit.h pcx.h typesize.h sprites.h
readinfo.o: readinfo.cc nfosprite.h typesize.h AllocArray.h
sprites.o: sprites.cc error.h typesize.h sprites.h pcx.h
error.obj: error.c error.h typesize.h
getopt.obj: getopt.c ./getopt.h
grfcomm.obj: grfcomm.c error.h typesize.h path.h grfcomm.h
grfmerge.obj: grfmerge.c ./getopt.h typesize.h version.h
path.obj: path.c path.h typesize.h
grfcodec.obj: grfcodec.cc ./getopt.h pcx.h typesize.h sprites.h pcxsprit.h \
  ttdpal.h grfcomm.h info.h nfosprite.h AllocArray.h error.h version.h \
  conv.h path.h
grfdiff.obj: grfdiff.cc ./getopt.h error.h typesize.h sprites.h pcx.h \
  grfcomm.h grfmrg.h path.h version.h
info.obj: info.cc info.h pcxsprit.h pcx.h typesize.h sprites.h nfosprite.h \
  AllocArray.h error.h
pcx.obj: pcx.cc pcx.h typesize.h error.h
pcxsprit.obj: pcxsprit.cc pcxsprit.h pcx.h typesize.h sprites.h
readinfo.obj: readinfo.cc nfosprite.h typesize.h AllocArray.h
sprites.obj: sprites.cc error.h typesize.h sprites.h pcx.h
